    const projects = {
        coffeepeople: {
            id: "coffeepeople",
            heading: "Book Cover",
            cover_title: "Coffee People",
            cover_img: "./images/projects/bookcovers/coffeepeople/cover.png",
            banner: "./images/projects/bookcovers/coffeepeople/banner.png",
            title: "Coffee People Illustrated Book Cover",
            year: "2024",
            client: "Ashley Claire",
            location: "United States",
            category: "Book Covers",
            filter: ["Books"],
            software: ["./images/icons/illustrator-icon.png", "./images/icons/procreate-icon.png"],
            brief: "Coffee People is the first book by Author Ashley Claire. Its a romance novel, about the character Sarah, a coffee shop owner, with flowers on every table. Her Coffee Shop is truly  her whole life, so when she learns a new coffee chain is  being built in Daisy Ridge, she will stop at nothing  to ensure that doesn’t happen.  Ethan is a man in a suit who has come to town  to open a coffee chain right down the road from Sarah’s quaint  coffee shop. Sarah starts to fall for a new guy in her life, Ethan,  one evening on a blind date, when she realizes he happens to be  her new arch-enemy.",
            sketch_desc: "She wanted to Sarah to be like Jessica Day, wearing black leggings, oversized band tees, hair up in a bun, black converse. And Ethan like Henry Cavil in suit,  and a Rolex from this dad on his wrist, which is part of the story. An obviously both of them holding an ice-coffee, since the story is about coffee shops. White flowers are a theme throughout and one of the idea was maybe the “o”s in the title could be a coffee ring?",
            sketch_img: ["./images/projects/bookcovers/coffeepeople/sketch-01.png"],
            final_desc: "She loved the 1st concept more and decided to proceed with it. The front cover included half body character illustration with the background of 2 different coffee shops. The background was split into 2 to show that they are from different backgrounds. I choose the orange and brown colour palette to suit the coffee theme and a touch of green to represent Starbucks . She wanted both ebook and paperback covers. This was my 2nd cover design and I loved working on it. ",
            final_img: ["./images/projects/bookcovers/coffeepeople/final-01.png"],   
            extra_img: ["./images/projects/bookcovers/coffeepeople/extras-01.png", "./images/projects/bookcovers/coffeepeople/extras-02.png", "./images/projects/bookcovers/coffeepeople/extras-03.png", "./images/projects/bookcovers/coffeepeople/extras-04.png", "./images/projects/bookcovers/coffeepeople/extras-05.png", "./images/projects/bookcovers/coffeepeople/extras-06.png", "./images/projects/bookcovers/coffeepeople/extras-07.png"],        
            review: ["OH MY GOSHHHH!!! You’re amazing, I adore it. I love everything about this cover. You are the best!"],
            client_img: ["./images/projects/bookcovers/coffeepeople/client.png"],
            client_role: ["Romance Author"],
            client_place: ["United States"],
        },

        lissmontoya: {
            id: "lissmontoya",
            heading: "Branding",
            cover_title: "Liss Montoya",
            cover_img: "./images/projects/branding/lissmontoya/cover.jpg",
            banner: "./images/projects/branding/lissmontoya/banner.jpg",
            title: "Liss Montoya Author Branding",
            year: "2025",
            client: "Liss Montoya",
            location: "United States",
            category: "Logo & Branding",
            filter: ["brand"],
            software: ["./images/icons/illustrator-icon.png", "./images/icons/procreate-icon.png"],
            brief: "Liss Montoya is the pen name of a Romance Author from United States. She writes Swoony, Sexy and Heartfelt Romance Novels. She want a logo, branding and event material designs for herself as a Author. She love to add flowers, bows and cherry to her designs. And colors preferred are pinks and greens.",
            sketch_desc: "",
            sketch_img: ["./images/projects/branding/lissmontoya/sketch-01.jpg"],
            final_desc: "",
            final_img: ["./images/projects/branding/lissmontoya/final-01.jpg"],   
            extra_img: [],        
            review: ["A huge shoutout to @gloinkdesigns for the AMAZING branding she did for me. I'm head over heels in love with it! Can't wait to display the banner in the upcoming signings 🫶🏽"],
            client_img: ["./images/projects/branding/lissmontoya/client.png"],
            client_role: ["Romance Author"],
            client_place: ["United States"],
        },

        bibliobarbie: {
            id: "bibliobarbie",
            heading: "Branding",
            cover_title: "Biblio Barbie",
            cover_img: "./images/projects/branding/bibliobarbie/cover.jpg",
            banner: "./images/projects/branding/bibliobarbie/banner.jpg",
            title: "Biblio Barbie Author Branding",
            year: "2025",
            client: "Danelle (Biblio Barbie)",
            location: "United States",
            category: "Logo & Branding",
            filter: ["brand"],
            software: ["./images/icons/illustrator-icon.png", "./images/icons/procreate-icon.png"],
            brief: "Biblio Barbie is the pen name of Danelle, a Romace Author. She need a typography logo and banner for her social media and shop. Elements to include - Heart, Space elements, Stars, monsters etc. with a fun and girly font. Colour prefered is shades of pink.",
            sketch_desc: "",
            sketch_img: ["./images/projects/branding/bibliobarbie/sketch-01.jpg"],
            final_desc: "",
            final_img: ["./images/projects/branding/bibliobarbie/final-01.jpg"],   
            extra_img: [],        
            review: ["Absolutely love my new branding! Thank you for a super easy and fun process 👏😍"],
            client_img: ["./images/projects/branding/bibliobarbie/client.png"],
            client_role: ["Romance Author"],
            client_place: ["United States"],
        },

        nailedbykaitlin: {
            id: "nailedbykaitlin",
            heading: "Branding",
            cover_title: "Nailed by Kaitlin",
            cover_img: "./images/projects/branding/nailedbykaitlin/cover.jpg",
            banner: "./images/projects/branding/nailedbykaitlin/banner.jpg",
            title: "Nialed by Kaitlin - Nail Artist Logo & Branding",
            year: "2025",
            client: "Kaitlin Wiley",
            location: "Michigan, United States",
            category: "Logo & Branding",
            filter: ["brand", "portrait"],
            software: ["./images/icons/illustrator-icon.png", "./images/icons/procreate-icon.png"],
            brief: "Nailed by Kaitlin is a Michigan-based nail artistry brand by Kaitlin Wiley, a nail tech apprentice at Glossed Nail Bar. She envisions a cool, badass, dark-vibe portrait logo & branding that reflects her bold and edgy aesthetic. She wants a portrait, logo and business card for her brand.",
            sketch_desc: "",
            sketch_img: ["./images/projects/branding/nailedbykaitlin/sketch-01.jpg"],
            final_desc: "",
            final_img: ["./images/projects/branding/nailedbykaitlin/final-01.jpg"],   
            extra_img: [],        
            review: ["She is AMAZING 👏 I am OBSESSED with my adorable logo 🥹 I love them so much! Thank you! If you need a business logo, book cover or cute illustration of yourself for fun, you have to check out gloinkdesigns! She is the sweetest and litterally is the BEST!"],
            client_img: ["./images/projects/branding/nailedbykaitlin/client.png"],
            client_role: ["Nail Artist"],
            client_place: [" Michigan, United States"],
        },

        ashleyclairebrand: {
            id: "ashleyclairebrand",
            heading: "Branding",
            cover_title: "Ashley Claire Branding",
            cover_img: "./images/projects/branding/ashleyclaire/cover.jpg",
            banner: "./images/projects/branding/ashleyclaire/banner.jpg",
            title: "Ashley Claire Author Branding",
            year: "2025",
            client: "Ashley Claire",
            location: "United States",
            category: "Logo & Branding",
            filter: ["brand"],
            software: ["./images/icons/illustrator-icon.png", "./images/icons/procreate-icon.png"],
            brief: "Ashley Claire is a Romance & Fantasy writer. She needs a Logo, Business Card and table runner for her brand as an Author. She likes to include dragons, pink lilies and ice coffee to the logo. Colours prefered are green and pink. And her Tagline is where 'sweethearts and sword fights share the spotlight'",
            sketch_desc: "",
            sketch_img: ["./images/projects/branding/ashleyclaire/sketch-01.jpg"],
            final_desc: "",
            final_img: ["./images/projects/branding/ashleyclaire/final-01.jpg"],   
            extra_img: [],        
            review: ["You're the best 🥹🫶 I absolutely love the little “ac” dragon 💖"],
            client_img: ["./images/projects/branding/ashleyclaire/client.png"],
            client_role: ["Romance & Fantasy Author"],
            client_place: ["United States"],
        },

        italianbreak: {
            id: "italianbreak",
            heading: "Book Cover",
            cover_title: "The Italian Break",
            cover_img: "./images/projects/bookcovers/theitalianbreak/cover.png",
            banner: "./images/projects/bookcovers/theitalianbreak/banner.png",
            title: "The Italian Break Illustrated Book Cover",
            year: "2024",
            client: "Amy Lamb",
            location: "United Kingdom",
            category: "Book Covers",
            filter: ["Books"],
            software: ["./images/icons/illustrator-icon.png", "./images/icons/procreate-icon.png"],
            brief: "The story revolves around Cassie Lawson, a lonely London lawyer. Cassie has built her adult life around independence and stability. Her professional life is everything she could have dreamed of, but her personal life…well, she doesn’t really have one. However, life has other plans. When Cassie's routine is interrupted to attend her sister’s wedding, in Florence. The wedding couldn’t have come at a worse time with Cassie's hectic schedule. On the way to Florence, Cassie bumps into Leon Armstrong, a cocky, optimistic, irritating man, but it’s ok – she only has to deal with him for the two hour plane journey, right? That’s what she thinks, until he turns up at the villa where her sister is getting married and will also be around for the next two weeks. When the pair are thrown together on multiple occasions, with what originally starts out as wedding duties, Cassie soon learns that maybe she needs to take a leaf out of Leon’s adventurous book, and that, maybe, there is more to life than a career.",
            sketch_desc: "She wanted the title to reflect the connect of the story with wines and add wine yard as background.",
            sketch_img: ["./images/projects/bookcovers/theitalianbreak/sketch-01.png"],
            final_desc: "",
            final_img: ["./images/projects/bookcovers/theitalianbreak/final-01.png"],   
            extra_img: ["./images/projects/bookcovers/theitalianbreak/extras-01.png", "./images/projects/bookcovers/theitalianbreak/extras-02.png", "./images/projects/bookcovers/theitalianbreak/extras-03.png", "./images/projects/bookcovers/theitalianbreak/extras-04.png", "./images/projects/bookcovers/theitalianbreak/extras-05.png", "./images/projects/bookcovers/theitalianbreak/extras-06.png"],        
            review: ["When creating the book cover I wanted something that represented my book. I wanted the cover to look like the words that are within my book. I love the way @gloinkdesigns has entwined my title, I had known the title for so long but when sending it out to early readers it was known as TIB and entwinting those letters together is just a reminder of how this started. Athira did the most wonderful job! I couldn't recommend her enough. Thank you so so much ❤️"],
            client_img: ["./images/projects/bookcovers/theitalianbreak/client.png"],
            client_role: ["Romance Author"],
            client_place: ["United States"],
        },

        rebelromance: {
            id: "rebelromance",
            heading: "Branding",
            cover_title: "Rebel Romance Bookstore",
            cover_img: "./images/projects/branding/rebelromance/cover.png",
            banner: "./images/projects/branding/rebelromance/banner.png",
            title: "Rebel Romance Bookstore Branding",
            year: "2025",
            client: "Elsie Smith",
            location: "United States",
            category: "Logo & Branding",
            filter: ["brand"],
            software: ["./images/icons/illustrator-icon.png", "./images/icons/procreate-icon.png"],
            brief: "Rebel Romance is a mobile (moving) fantasy and romance bookstore by Author Elise Smith, coming in North California. She wants a logo & branding and would like to have some sort of foliage/florals in the branding somewhere because she loves that vibe and they also have a small plant section. For the alt logo, they needed something that will look good printed in a single color for tshirts and other merch.",
            sketch_desc: "",
            sketch_img: ["./images/projects/branding/rebelromance/sketch-01.png"],
            final_desc: "",
            final_img: ["./images/projects/branding/rebelromance/final-01.png"],   
            extra_img: [],        
            review: ["Its all so pretty! I am so glad I went with you. You've captured everything perfectly and I am so in love with it all.I am still obsessed with everything you created!"],
            client_img: ["./images/projects/branding/rebelromance/client.png"],
            client_role: ["Romance Author"],
            client_place: ["United States"],
        },

        withthisring: {
            id: "withthisring",
            heading: "Book Cover",
            cover_title: "With this Ring",
            cover_img: "./images/projects/bookcovers/withthisring/cover.jpg",
            banner: "./images/projects/bookcovers/withthisring/banner.jpg",
            title: "With this Ring Illustrated Book Cover",
            year: "2023",
            client: "Samantha King",
            location: "United Kingdom",
            category: "Book Covers",
            filter: ["Books"],
            software: ["./images/icons/illustrator-icon.png", "./images/icons/procreate-icon.png"],
            brief: "The story is about Sebation who is attending the wedding of his brother and his ex fiance. There is just one problem. His family expect him to have a fiance in toe. After all he told them he was engaged. It was a lie. Pippa is fleeing wanting to start over when she meets Sebation. She doesn’t expect to be offered one hundred thousand dollars if she marries him. After sebastion’s dad passes away he learns the terms of his dads will. In order to get his inheritence he must be married one whole year. But that’s not a problem he’s engaged, except its not real. Now sebation asks Pippa to marry him in order to get his inheritence. After all everyone already believes they are engaged. There are just two ruled - 1) Always discusses with the other before making an discussions and 2) Don’t catch feelings",
            sketch_desc: "She wanted rings along with the book title",
            sketch_img: ["./images/projects/bookcovers/withthisring/sketch-01.jpg"],
            final_desc: "",
            final_img: ["./images/projects/bookcovers/withthisring/final-01.jpg"],   
            extra_img:[],        
            review: ["Honestly it's perfect.  Your work is amazing!"],
            client_img: ["./images/projects/bookcovers/withthisring/client.png"],
            client_role: ["Romance Author"],
            client_place: ["United States"],
        },   
        
        sinistersets: {
            id: "sinistersets",
            heading: "Branding",
            cover_title: "Sinister Sets",
            cover_img: "./images/projects/branding/sinistersets/cover.jpg",
            banner: "./images/projects/branding/sinistersets/banner.jpg",
            title: "Sinister Sets - Nail Press On Brand Logo",
            year: "2025",
            client: "Kaitlin Wiley",
            location: "Michigan, United States",
            category: "Logo & Branding",
            filter: ["brand"],
            software: ["./images/icons/illustrator-icon.png", "./images/icons/procreate-icon.png"],
            brief: "Sinister Sets is a Nail Press On Business by a Michigan-based nail artist Kaitlin Wiley, a nail tech apprentice at Glossed Nail Bar. She envisions a cool, badass, neon, dark-vibe portrait logo & branding that reflects her bold and edgy aesthetic.",
            sketch_desc: "",
            sketch_img: ["./images/projects/branding/sinistersets/sketch-01.jpg"],
            final_desc: "",
            final_img: ["./images/projects/branding/sinistersets/final-01.jpg"],   
            extra_img: [],        
            review: ["@gloinkdesigns has done it again! In love with my logo for my press on business."],
            client_img: ["./images/projects/branding/sinistersets/client.png"],
            client_role: ["Nail Artist"],
            client_place: [" Michigan, United States"],
        },
     };


    