    const projects = {
        coffeepeople: {
            id: "coffeepeople",
            heading: "Book Cover",
            cover_title: "Coffee People",
            cover_img: "./images/projects/bookcovers/coffeepeople/cover.png",
            banner: "./images/projects/bookcovers/coffeepeople/banner.png",
            title: "Coffee People Illustrated Book Cover",
            year: "2024",
            client: "Ashley Claire",
            location: "United States",
            category: "Books",
            software: ["./images/icons/illustrator-icon.png", "./images/icons/procreate-icon.png"],
            brief: "Coffee People is the first book by Author Ashley Claire. Its a romance novel, about the character Sarah, a coffee shop owner, with flowers on every table. Her Coffee Shop is truly  her whole life, so when she learns a new coffee chain is  being built in Daisy Ridge, she will stop at nothing  to ensure that doesn’t happen.  Ethan is a man in a suit who has come to town  to open a coffee chain right down the road from Sarah’s quaint  coffee shop. Sarah starts to fall for a new guy in her life, Ethan,  one evening on a blind date, when she realizes he happens to be  her new arch-enemy.",
            sketch_desc: "She wanted to Sarah to be like Jessica Day, wearing black leggings, oversized band tees, hair up in a bun, black converse. And Ethan like Henry Cavil in suit,  and a Rolex from this dad on his wrist, which is part of the story. An obviously both of them holding an ice-coffee, since the story is about coffee shops. White flowers are a theme throughout and one of the idea was maybe the “o”s in the title could be a coffee ring?",
            sketch_img: ["./images/projects/bookcovers/coffeepeople/sketch-01.png"],
            final_desc: "She loved the 1st concept more and decided to proceed with it. The front cover included half body character illustration with the background of 2 different coffee shops. The background was split into 2 to show that they are from different backgrounds. I choose the orange and brown colour palette to suit the coffee theme and a touch of green to represent Starbucks . She wanted both ebook and paperback covers. This was my 2nd cover design and I loved working on it. ",
            final_img: ["./images/projects/bookcovers/coffeepeople/final-01.png"],   
            extra_img: ["./images/projects/bookcovers/coffeepeople/extras-01.png", "./images/projects/bookcovers/coffeepeople/extras-02.png", "./images/projects/bookcovers/coffeepeople/extras-03.png", "./images/projects/bookcovers/coffeepeople/extras-04.png", "./images/projects/bookcovers/coffeepeople/extras-05.png", "./images/projects/bookcovers/coffeepeople/extras-06.png", "./images/projects/bookcovers/coffeepeople/extras-07.png"],        
            review: ["OH MY GOSHHHH!!! You’re amazing, I adore it. I love everything about this cover. You are the best!"],
            client_img: ["./images/projects/bookcovers/coffeepeople/client-ashley claire.png"],
            client_role: ["Romance Author"],
            client_place: ["United States"],
        },

        coffeepeople2: {
            id: "coffeepeople2",
            heading: "Book Cover",
            cover_title: "Coffee People",
            cover_img: "./images/projects/bookcovers/coffeepeople/cover.png",
            banner: "./images/projects/bookcovers/coffeepeople/banner.png",
            title: "Coffee People Illustrated Book Cover",
            year: "2024",
            client: "Ashley Claire",
            location: "United States",
            category: "Books",
            software: ["./images/icons/illustrator-icon.png", "./images/icons/procreate-icon.png"],
            brief: "Coffee People is the first book by Author Ashley Claire. Its a romance novel, about the character Sarah, a coffee shop owner, with flowers on every table. Her Coffee Shop is truly  her whole life, so when she learns a new coffee chain is  being built in Daisy Ridge, she will stop at nothing  to ensure that doesn’t happen.  Ethan is a man in a suit who has come to town  to open a coffee chain right down the road from Sarah’s quaint  coffee shop. Sarah starts to fall for a new guy in her life, Ethan,  one evening on a blind date, when she realizes he happens to be  her new arch-enemy.",
            sketch_desc: "She wanted to Sarah to be like Jessica Day, wearing black leggings, oversized band tees, hair up in a bun, black converse. And Ethan like Henry Cavil in suit,  and a Rolex from this dad on his wrist, which is part of the story. An obviously both of them holding an ice-coffee, since the story is about coffee shops. White flowers are a theme throughout and one of the idea was maybe the “o”s in the title could be a coffee ring?",
            sketch_img: ["./images/projects/bookcovers/coffeepeople/sketch-01.png"],
            final_desc: "She loved the 1st concept more and decided to proceed with it. The front cover included half body character illustration with the background of 2 different coffee shops. The background was split into 2 to show that they are from different backgrounds. I choose the orange and brown colour palette to suit the coffee theme and a touch of green to represent Starbucks . She wanted both ebook and paperback covers. This was my 2nd cover design and I loved working on it. ",
            final_img: ["./images/projects/bookcovers/coffeepeople/final-01.png"],   
            extra_img: ["./images/projects/bookcovers/coffeepeople/extras-01.png", "./images/projects/bookcovers/coffeepeople/extras-02.png", "./images/projects/bookcovers/coffeepeople/extras-03.png", "./images/projects/bookcovers/coffeepeople/extras-04.png", "./images/projects/bookcovers/coffeepeople/extras-05.png", "./images/projects/bookcovers/coffeepeople/extras-06.png", "./images/projects/bookcovers/coffeepeople/extras-07.png"],        
            review: ["OH MY GOSHHHH!!! You’re amazing, I adore it. I love everything about this cover. You are the best!"],
            client_role: ["Romance Author"],
            client_place: ["United States"],
        },

        coffeepeople3: {
            id: "coffeepeople3",
            heading: "Book Cover",
            cover_title: "Coffee People",
            cover_img: "./images/projects/bookcovers/coffeepeople/cover.png",
            banner: "./images/projects/bookcovers/coffeepeople/banner.png",
            title: "Coffee People Illustrated Book Cover",
            year: "2024",
            client: "Ashley Claire",
            location: "United States",
            category: "Books",
            software: ["./images/icons/illustrator-icon.png", "./images/icons/procreate-icon.png"],
            brief: "Coffee People is the first book by Author Ashley Claire. Its a romance novel, about the character Sarah, a coffee shop owner, with flowers on every table. Her Coffee Shop is truly  her whole life, so when she learns a new coffee chain is  being built in Daisy Ridge, she will stop at nothing  to ensure that doesn’t happen.  Ethan is a man in a suit who has come to town  to open a coffee chain right down the road from Sarah’s quaint  coffee shop. Sarah starts to fall for a new guy in her life, Ethan,  one evening on a blind date, when she realizes he happens to be  her new arch-enemy.",
            sketch_desc: "She wanted to Sarah to be like Jessica Day, wearing black leggings, oversized band tees, hair up in a bun, black converse. And Ethan like Henry Cavil in suit,  and a Rolex from this dad on his wrist, which is part of the story. An obviously both of them holding an ice-coffee, since the story is about coffee shops. White flowers are a theme throughout and one of the idea was maybe the “o”s in the title could be a coffee ring?",
            sketch_img: ["./images/projects/bookcovers/coffeepeople/sketch-01.png"],
            final_desc: "She loved the 1st concept more and decided to proceed with it. The front cover included half body character illustration with the background of 2 different coffee shops. The background was split into 2 to show that they are from different backgrounds. I choose the orange and brown colour palette to suit the coffee theme and a touch of green to represent Starbucks . She wanted both ebook and paperback covers. This was my 2nd cover design and I loved working on it. ",
            final_img: ["./images/projects/bookcovers/coffeepeople/final-01.png"],   
            extra_img: ["./images/projects/bookcovers/coffeepeople/extras-01.png", "./images/projects/bookcovers/coffeepeople/extras-02.png", "./images/projects/bookcovers/coffeepeople/extras-03.png", "./images/projects/bookcovers/coffeepeople/extras-04.png", "./images/projects/bookcovers/coffeepeople/extras-05.png", "./images/projects/bookcovers/coffeepeople/extras-06.png", "./images/projects/bookcovers/coffeepeople/extras-07.png"],        
            review: ["OH MY GOSHHHH!!! You’re amazing, I adore it. I love everything about this cover. You are the best!"],
            client_role: ["Romance Author"],
            client_place: ["United States"],
        }
     };


    